// <auto-generated />
namespace Fenergo.Ui.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class populateHardwareTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populateHardwareTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "202006121957456_populateHardwareTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
